/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 meat-transformed.glb --output /Users/mschmutz/work/web-bbq/frontend/src/Components/bbq/Meat.tsx --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Cube001: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    inside: THREE.MeshStandardMaterial
    Bone: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationAction[]
}

export function Meat(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/meat-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.inside} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Bone} position={[1.149, 0, 0]} scale={0.441} />
    </group>
  )
}

useGLTF.preload('/meat-transformed.glb')
