/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Meat(props) {
	const { nodes, materials } = useGLTF('/meat.glb')
	return (
		<group {...props} dispose={null}>
			<group rotation={[0, 0, -Math.PI / 2]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder001_1.geometry}
					material={materials['Material.001']}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder001_2.geometry}
					material={materials.inside}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials.Bone}
					position={[0, 1.149, 0]}
					rotation={[0, 0, Math.PI / 2]}
					scale={0.441}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube002.geometry}
					material={materials.Bone}
					position={[0, 1.566, 0]}
					rotation={[0, 0, Math.PI / 2]}
					scale={0.441}
				/>
			</group>
		</group>
	)
}

useGLTF.preload("/meat.glb");
